CREATE DATABASE hospital;
USE hospital;

CREATE TABLE IF NOT EXISTS genders (
	`id` INT(11) AUTO_INCREMENT,
	`gender` VARCHAR(6) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS nationalities (
	`id` INT(11) AUTO_INCREMENT,
	`nationality` VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS nationalityTypes (
	`id` INT(11) AUTO_INCREMENT,
	`type` VARCHAR(11) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS departments (
	`id` INT(11) AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS users (
	`id` INT(11) AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` CHAR(60) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS auth_tokens (
	`id` INTEGER(11) NOT NULL AUTO_INCREMENT,
	`selector` CHAR(12),
	`token` CHAR(64),
	`user_id` INTEGER(11) NOT NULL,
	`expires` DATETIME,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`user_id`) REFERENCES users (`id`) ON DELETE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS cities (
	`id` INT(11) AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS areas (
	`id` INT(11) AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`city_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`city_id`) REFERENCES cities (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE(`name`, `city_id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS machineTypes (
	`id` INT(11) AUTO_INCREMENT,
	`type` VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS machines (
	`id` INT(11) AUTO_INCREMENT,
	`arName` VARCHAR(100) NOT NULL,
	`enName` VARCHAR(100) NOT NULL,
	`description` VARCHAR(255) DEFAULT NULL,
	`type_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`type_id`) REFERENCES machineTypes (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE(`arName`, `type_id`),
	UNIQUE(`enName`, `type_id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS transfers (
	`id` INT(11) AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS positionRoles (
	`id` INT(11) AUTO_INCREMENT,
	`role` VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS employees (
	`id` INT(11) AUTO_INCREMENT,
	`firstName` VARCHAR(30) NOT NULL,
	`middleName` VARCHAR(30) NOT NULL,
	`lastName` VARCHAR(30) NOT NULL,
	`civil_id` CHAR(12) NOT NULL UNIQUE,
	`passport_number` VARCHAR(9) DEFAULT NULL,
	`image` VARCHAR(255) DEFAULT NULL,
	`dob` DATE NOT NULL,
	`hireDate` DATE NOT NULL,
	`creationTime` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`modificationTime` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	`department_id` INT(11) NOT NULL,
	`gender_id` INT(11) NOT NULL,
	`nationality_id` INT(11) NOT NULL,
	`nationalityType_id` INT(11) NOT NULL,
	`positionRole_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`department_id`) REFERENCES departments (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`gender_id`) REFERENCES genders (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`nationality_id`) REFERENCES nationalities (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`nationalityType_id`) REFERENCES nationalityTypes (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`positionRole_id`) REFERENCES positionRoles (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS patients (
	`id` INT(11) AUTO_INCREMENT,
	`firstName` VARCHAR(30) NOT NULL,
	`middleName` VARCHAR(30) NOT NULL,
	`lastName` VARCHAR(30) NOT NULL,
	`civil_id` CHAR(12) NOT NULL UNIQUE,
	`passport_number` VARCHAR(9) DEFAULT NULL,
	`dob` DATE NOT NULL,
	`creationTime` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`modificationTime` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	`image` VARCHAR(255) DEFAULT NULL,
	`notes` VARCHAR(255) DEFAULT NULL,
	`gender_id` INT(11) NOT NULL,
	`nationality_id` INT(11) NOT NULL,
	`nationalityType_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`gender_id`) REFERENCES genders (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`nationality_id`) REFERENCES nationalities (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`nationalityType_id`) REFERENCES nationalityTypes (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS phoneNumbers (
	`id` INT(11) AUTO_INCREMENT,
	`number` VARCHAR(11) NOT NULL,
	`typeDiscriminator` VARCHAR(255) NOT NULL,
	`phoneOf_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE (`number`, `typeDiscriminator`, `phoneOf_id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS articles (
	`id` INT(11) AUTO_INCREMENT,
	`price` NUMERIC(8, 2),
	`date` DATE NOT NULL,
	`patient_id` INT(11) NOT NULL,
	`transfer_id` INT(11) DEFAULT NULL,
	`machine_id` INT(11) DEFAULT NULL,
	`department_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`patient_id`) REFERENCES patients (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`transfer_id`) REFERENCES transfers (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`machine_id`) REFERENCES machines (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`department_id`) REFERENCES departments (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS disabilities (
	`id` INT(11) AUTO_INCREMENT,
	`description` VARCHAR(255) DEFAULT NULL,
	`amount` NUMERIC(8, 2) NOT NULL,
	`article_id` INT(11) NOT NULL,
	`date` DATE NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`article_id`) REFERENCES articles (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS financialAids (
	`id` INT(11) AUTO_INCREMENT,
	`description` VARCHAR(255) DEFAULT NULL,
	`amount` NUMERIC(8, 2) NOT NULL,
	`article_id` INT(11) NOT NULL,
	`date` DATE NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`article_id`) REFERENCES articles (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS receipts (
	`id` INT(11) AUTO_INCREMENT,
	`receiptDate` DATE NOT NULL,
	`deliveryDate` DATE NOT NULL,
	`article_id` INT(11) NOT NULL,
	`machine_id` INT(11) NOT NULL,
	`employee_id` INT(11) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`article_id`) REFERENCES articles (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`machine_id`) REFERENCES machines (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (`employee_id`) REFERENCES employees (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

INSERT INTO `users` (`id`, `username`, `password`) VALUES
(1, 'alansary', '$2y$11$bVW9W6l7Jbuy0l9Gsx4RMuAPS2kI33mICBkeXlmDjfG6DwWd6ar/6');